; Left to right, top to bottom

	.byte TILE_BORDER0, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_PANEL1, TILE_HORZPATH, TILE_HORZSTOP, TILE_HORZPATH, TILE_PANEL2, TILE_HORZPATH, TILE_HORZSTOP, TILE_HORZPATH, TILE_PANEL4, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_BORDER0
	.byte TILE_BORDER0, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_VERTPATH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_VERTPATH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_VERTPATH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_BORDER0
	.byte TILE_BORDER0, TILE_FAKEPATH, TILE_START, TILE_HORZPATH, TILE_CORNERSTOP, TILE_LOCKHORZ, TILE_HORZSTOP, TILE_DANCINGBUSH, TILE_VERTSTOP, TILE_HORZPATH, TILE_PANEL3, TILE_HORZPATH, TILE_TOADHOUSE, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_BORDER0
	.byte TILE_BORDER0, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_VERTPATH, TILE_DANCINGBUSH, TILE_VERTPATH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_BORDER0
	.byte TILE_BORDER0, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_SPADEBONUS, TILE_HORZPATH, TILE_FORT, TILE_HORZPATH, TILE_CORNERSTOP, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_RIVER_TL, TILE_RIVER_HORZ, TILE_RIVER_TR, TILE_DANCINGBUSH, TILE_BORDER0
	.byte TILE_BORDER0, TILE_DANCINGBUSH, TILE_SPACE, TILE_SPACE, TILE_VERTPATH, TILE_SPACE, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_DANCINGBUSH, TILE_RIVER_TL, TILE_RIVER_HORZ, TILE_RIVER_BR, TILE_CASTLETOP, TILE_RIVER_VERT, TILE_DANCINGBUSH, TILE_BORDER0
	.byte TILE_BORDER0, TILE_SPACE, TILE_SPACE, TILE_ROCK, TILE_VERTSTOP, TILE_ROCK, TILE_SPACE, TILE_DANCINGBUSH, TILE_STOP, TILE_BRIDGE, TILE_HORZSTOP, TILE_HORZPATH, TILE_CASTLEBOTTOM, TILE_RIVER_VERT, TILE_DANCINGBUSH, TILE_BORDER0
	.byte TILE_BORDER0, TILE_SPACE, TILE_ROCK, TILE_ROCK, TILE_VERTPATH, TILE_ROCK, TILE_ROCK, TILE_SPACE, TILE_VERTPATH, TILE_RIVER_VERT, TILE_SPACE, TILE_SPACE, TILE_SPACE, TILE_RIVER_VERT, TILE_DANCINGBUSH, TILE_BORDER0
	.byte TILE_BORDER0, TILE_SPACE, TILE_ROCK, TILE_ROCK, TILE_PANEL5, TILE_HORZPATH, TILE_HORZSTOP, TILE_HORZPATH, TILE_PANEL6, TILE_RIVER_BL, TILE_RIVER_HORZ, TILE_RIVER_HORZ, TILE_RIVER_HORZ, TILE_RIVER_BR, TILE_DANCINGBUSH, TILE_BORDER0

	.byte $FF
